version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000

# NOTA: para obtener el password ejecutar lo siguiente
# docker exec <jenkins> cat /var/jenkins_home/secrets/initialAdminPassword
