services:
  # * ===============
  # * Base de datos
  # * ===============
  database:
    image: postgres:15-alpine
    # Equivale a nombre de servidor
    container_name: postgres_database
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: usuario_postgres
      POSTGRES_DB: test_database
  # * ===============
  # * Panel de admin
  # * ===============
  panel:
    profiles:
      - pgadmin
    depends_on:
      - database
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8080:80
    # Acceso a base pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json
  # * ===============
  # * Panel (alt)
  # * ===============
  adminer:
    profiles:
      - adminer
    depends_on:
      - database
    container_name: adminer_admin
    image: adminer:5-standalone
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce dump-json dump-date dump-xml dump-zip"
      ADMINER_DESIGN: "dracula"
