version: '3'

services:
  oracleDB:
    container_name: oracle_container
    image: container-registry.oracle.com/database/express:18.4.0-xe
    platform: linux/amd64
    # image: oraclelinux:9
    restart: always
    # volumes:
    #  - ./ora_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: Oracle#1234
