services:
  windows:
    # image: dockurr/windows-arm
    container_name: windows
    environment:
      VERSION: "tiny10"
      LANGUAGE: "Spanish"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./c32:/storage
    stop_grace_period: 2m
