version: "3"

services:
  mongoDB:
    container_name: pokedb
    ports:
      - 27017:27017
    image: mongo:6.0
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME_GG
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always
    command: "--auth"

  dbPanel:
    depends_on:
      - mongoDB
    container_name: mongoPanel
    ports:
      - 8080:8081
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: USERNAME_GG
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: pokedb
    restart: always

  node-app:
    depends_on:
      - mongoDB
    container_name: pokeApp
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    environment:
      MONGODB: mongodb://USERNAME_GG:123456@pokedb:27017
      DB_NAME: pokedb
    restart: always

volumes:
  mongo_vol:
    external: false
