version: "3"

services:
  mongoDB:
    container_name: pokeserver
    ports:
      - 27017:27017
    image: mongo:6.0
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME_GG
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always
    command: "--auth"

  dbPanel:
    depends_on:
      - mongoDB
    container_name: mongoPanel
    ports:
      - 8080:8081
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: USERNAME_GG
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: pokeserver
    restart: always

volumes:
  mongo_vol:
    external: false
