version: '3.2'

services:
  flutter:
    image: ghcr.io/cirruslabs/flutter:3.19.4
    container_name: flutter_env
    # La bandera de -dit para entrar al contenedor
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
