# Imagen + direccion base
FROM ubuntu:oracular
WORKDIR /home/workspace

# Para scripts locales
ENV PATH="$PATH:/root/.local/bin"

# Instalado updates + git + gitlab + nano + wget
# Configuraciones para shell personalizada
RUN apt update && apt upgrade -y && apt install git glab gh curl unzip wget nano -y 

# Configuración Oh My Posh
ENV POSH_FILE_NAME=wholespace.omp.json
RUN curl -s https://ohmyposh.dev/install.sh | bash -s 
COPY setup-shell.sh /usr/local/bin/setup-shell.sh
RUN chmod +x /usr/local/bin/setup-shell.sh

# Instalación de gdrive
RUN wget -O gdrive.tar.gz https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_arm.tar.gz && \
    tar -xzf gdrive.tar.gz -C /usr/local/bin && \
    chmod +x /usr/local/bin/gdrive && \
    rm gdrive.tar.gz