services:
  # * ===============
  # * Base de datos
  # * ===============
  database:
    # Este es el nombre del "server"
    container_name: sql_server_container
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    # platform: linux/amd64
    volumes:
      - ./database:/var/opt/mssql/data/
    ports:
      - "1333:1433"
    environment:
      MSSQL_SA_PASSWORD: Admin#1234
      ACCEPT_EULA: Y
  # * ===============
  # * Panel (alt)
  # * ===============
  adminer:
    profiles:
      - adminer
    depends_on:
      - database
    container_name: adminer_admin
    image: adminer:5.3.0-standalone
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      ADMINER_PLUGINS: "dump-alter dump-json dump-date dump-xml dump-zip tables-filter monaco tinymce"
      ADMINER_DESIGN: "dracula"
