version: "3"

services:
  adminer:
    container_name: adminerContainer
    image: adminer:5.3.0-standalone
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADM_INSTALL_MSSQL: true
      PHP_FPM_INSTALL_MSSQL: true
      WORKSPACE_INSTALL_MSSQL: true
      ADMINER_PLUGINS: "dump-alter dump-json dump-date dump-xml dump-zip tables-filter monaco tinymce"
      ADMINER_DESIGN: "dracula"
