services:
  db:
    container_name: databaseContainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    # platform: linux/amd64
    volumes:
      - ./sql_server:/var/opt/mssql/data/
    ports:      
      - '1333:1433'
    environment:
      MSSQL_SA_PASSWORD: Admin#1234
      ACCEPT_EULA: Y
