services:
  # * ===============
  # * Base de datos
  # * ===============
  database:
    # Este es el nombre del "server"
    container_name: mariadb_container
    ports:
      - 3306:3306
    image: mariadb:jammy
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: 12345
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: testdb
  # * ===============
  # * Panel de admin
  # * ===============
  panel:
    profiles:
      - phpmyadmin
    depends_on:
      - database
    container_name: phpmyadmin_container
    ports:
      - 8080:80
    image: phpmyadmin:5.2.0-apache
    environment:
      - PMA_ARBITRARY=1
  # * ===============
  # * Panel (alt)
  # * ===============
  adminer:
    profiles:
      - adminer
    depends_on:
      - database
    container_name: adminer_admin
    image: adminer:5-standalone
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce dump-json dump-date dump-xml dump-zip"
      ADMINER_DESIGN: "dracula"
